### ISSUE TITLE
Smart Life connection

### ISSUE THREAD

**Issue by jcwlim** [tizzen33/domoticz-tuyacloud-plugin#1]
Hi, I am trying this wonderful plugin now.
May I know does it work only with "Tuya"? Can it work with "Smart Life" which is another clone directly and mange by the Tuya company.
I have a switch (power plug) in the "Smart Life" app but it never pick up by the plugin.
I try to change the code under "params" - "from": "smart_life" still no go....

**Comment by jcwlim** [comment]
Is okay, solved it... instead of "from", just put "smart_life" under "bizType"

**Comment by tizzen33** [comment]
Hi
Thanks for using the plugin. Glad it worked out with the Smart Life account. I originally used the LSC Smart Connect app and couldn't figure out how to login but I guess I should have looked deeper into the 'bizType'.

Kind regards
tizzen

**Comment by jcwlim** [comment]
I created a video regarding this plugin too. 
[https://youtu.be/pBJZcwIDOUY](url)

I will soon will look into integrate light switch and other available devices. Scenes might be good option to look at as well too.
