### ISSUE TITLE
Requires python3-dev

### ISSUE THREAD

**Issue by yetanotherjr** [tizzen33/domoticz-tuyacloud-plugin#11]
Hi,

I followed the instructions, but the "Tuya Cloud" entry was not showing up.
After looking at the "Log" section in Domoticz, I found that python3-dev was missing.

I installed it (`sudo apt-get install python3-dev`) then restarted domoticz (`systemctl restart domoticz`) and the entry is now OK.

I don't know if it's relevant to add it in the prerequisites, just wanted to share :)

**Comment by tizzen33** [comment]
Hi,

Thanks for the info. I'm not really sure why it's necessary but good to know!
