### ISSUE TITLE
Re-work plugin by using tuyaha package to support more devices

### ISSUE THREAD

**Issue by tizzen33** [tizzen33/domoticz-tuyacloud-plugin#14]
I'm opening this issue myself as an informational thread while I work on rewriting the plugin to support more devices. I will make use of the [tuyaha](https://pypi.org/project/tuyaha/) package.

Stay tuned.

**Comment by Xenomes** [comment]
Hi tizzen,
I found this one, is this the same you wanna build?
https://github.com/guino/tuyaha

**Comment by tizzen33** [comment]
That's exactly what I was planning to do. Great! That means I don't have to spend my time on it :).

**Comment by Xenomes** [comment]
I was just experimenting with it, I cloned the Master of PaulAnnekov 0.0.7 and wget the plugin.py of guino in to it and that works!
I have RGB control, unfortunately no white channel support. 🤣

**Comment by tizzen33** [comment]
Great. I'm almost done with my switch to Home Assistant, so I think I'll put this plugin in the archive and refer to the one you found.
