### ISSUE TITLE
Wrong width in field Password and Mode1 

### ISSUE THREAD

**Issue by laplug** [tizzen33/domoticz-tuyacloud-plugin#18]
Hi @tizzen33,
Thanks for the nice plugin! Works just fine.
A small error in de xml part. The sizes of the field Password and Mode1 (countryCode) are mixed up:
Currently:
`        <param field="Password" label="Password" width="30px" required="true" default="" password="true"/>
        <param field="Mode1" label="countryCode" width="150px" required="true"/>
`
Should be:
`        <param field="Password" label="Password" width="150px" required="true" default="" password="true"/>
        <param field="Mode1" label="countryCode" width="30px" required="true"/>
`
I'm not a Python programmer, so I will probably not contribute anything meaningful :-(
But I'm looking forward to extension of the plugin to incorporate the kWh usage that is recorded by the SmartLife plugs.

BTW: I use it on Windows 10 machine
Domoticz Version: 2020.2 (build 12280)
Build Hash: f8711e9c1
Compile Date: 2020-08-28 11:52:32
dzVents Version: 3.0.11
Python Version: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:43:08) [MSC v.1926 32 bit (Intel)]
(Python-Dev seems to be included on the Windows version of Python)

**Comment by tizzen33** [comment]
Hi,

I was going to start re-working the plugin to use the full tuya API but it seems this has already been done by another developer. So I suggest you to use this plugin instead:
https://github.com/guino/tuyaha

Kind regards
Tizzen

**Comment by laplug** [comment]
Thanx!
