### ISSUE TITLE
I modified a little bit the code for lights

### ISSUE THREAD

**Issue by Tixav** [tizzen33/domoticz-tuyacloud-plugin#4]
on line 109 I addes
` if (createDomoticzDevice and tuya_device["ha_type"] == "light"):
                    Domoticz.Device(Name=tuya_device["name"],Unit=maxUnit+1,TypeName='Switch',DeviceID=tuya_device["id"]).Create()
                    Domoticz.Debug('Creating a {type} device with identifier {id}'.format(type=tuya_device["ha_type"],id=tuya_device["id"]))
`

on the line 141 I remove caps on True and False
  states = {'true': 1, 'false': 0}

Now I wolud like to dim the light but I do not know how I will do yet

**Comment by Xenomes** [comment]
Hi Tixav,
Nice! now I can turn on/off my RGBWW lamps. 👍

I also alter your code a little bit:
```
108                if (createDomoticzDevice and (tuya_device["ha_type"] == "light" or tuya_device["ha_type"] == "switch")):
109                    Domoticz.Device(Name=tuya_device["name"],Unit=maxUnit+1,TypeName="Switch",DeviceID=tuya_device["id"],Used=1).Create()
137        states = {'true': 1, 'false': 0}
```

**Comment by tizzen33** [comment]
Hi

I updated the code with your remarks and some small changes:

https://github.com/tizzen33/domoticz-tuyacloud-plugin/blob/93449c7b10bb8d76505a98ec4eb96a8ddba05967/plugin.py#L47
Added a new device type with image 0 = default light icon

https://github.com/tizzen33/domoticz-tuyacloud-plugin/blob/93449c7b10bb8d76505a98ec4eb96a8ddba05967/plugin.py#L108-L110
Use the device types to create the correct device
