### ISSUE TITLE
Compatibility with tuya wifi motion sensor ?

### ISSUE THREAD

**Issue by julienda** [tizzen33/domoticz-tuyacloud-plugin#5]
Hello, 

I just want to know if this plugin can be compliant with a tuya wifi motion sensor device ?

If not or can be compliant ???

Thanks by advance

**Comment by tizzen33** [comment]
Not at the moment since the plug-in only creates power sockets and lights (on/off).
If you install the plug-in and send me the start-up logs, I’ll check if it’s easy to implement.

I’m waiting on a Tuya Smoke Detector, should be the same principle.

**Comment by tizzen33** [comment]
Hi, it’s not compatible at the moment.

**Comment by karlzre** [comment]
Hi Tizzen33, 

I just bought a motion sensor from action shop, the brand LSC (tuya) 
I would like to send you the logs, could you give me the process to get it ? 
i enabled the logs verbose in domoticz hardware .
If these logs can help you to make the device available in you plug in .

**Comment by tizzen33** [comment]
Hi,
Go to Setup > Logs and there it will show when you enable the hardware. 
But I'm afraid it won't matter since support for this device is not available in the Home Assistant API that I reused for Domoticz. I believe it's not possible to add any 'sensor' to the platform such as motion or smoke.
