### ISSUE TITLE
Possible error in Tuyacloud together with Domoticz, Node-Red or may be not.

### ISSUE THREAD

**Issue by heinohein** [tizzen33/domoticz-tuyacloud-plugin#6]
First thank you for your application. It works great when used in only Domoticz. 
I have used it several times to add more Tuya like smart plug bought from Aliexpress and to "sync" changed names between the "Smart life" Android phone app and Domoticz. When I switch on/off a plug on the phone the icon changes in Domoticz, when I switch in Domoticz the changed status is visible in the phone app. Great.

I want to use these smart plugs in Domoticz and Node-Red, and I also like to see the powerconsumption measured by a plug.
 I run Domoticz V4.10726, Mosquitto MQTT broker 1.4.10 and Node-Red V1.0.6 on a Raspberry PI 3B  4.19.66-v7+ 

As you probaly know Domoticz sends a copy of the row of the Device table to topic domoticz/out when I change the status of the plug to on/off.  I defined in Node-Red a simple switch node and I filter incomming messages from domoticz/out on the relevant "idx". I also generate a small message with only the status of the switch topic domoticz/in when I change the switch in Node-Red.

When I change on/off in Domoticz, I see the switch in Node-Red/ui change as well. Great.
When I change the switch in Node-Red, I see the icon change in Domoticz, but the switching in the smart plug does not occur. So the power stays on/off as the status was.

Possibly this is an error in the Tuyacloud application, possibly it is an error in Domoticz, possibly I need to install something else. 
Do you have any idea what causes this problem? Could you please give me a hint how to solve this?

I have extracted the following logs

//Converted message from domoticz/out to switch
16-7-2020 20:39:37node: 95d6a158.34616msg.payload : boolean
true
//outgoing message from switch to domoticz/in
16-7-2020 20:39:39node: 95d6a158.34616msg.payload : string[22]
"{"idx":64, "nvalue":1}"

16-7-2020 20:39:40node: 95d6a158.34616msg.payload : boolean
true
//Incomming device row message from domoticz/out, switch is set on  
16-7-2020 20:39:41node: 95d6a158.34616domoticz/out : msg.payload : string[261]
"{?   "Battery" : 255,?   "RSSI" : 12,?   "description" : "",?   "dtype" : "Light/Switch",?   "id" : "bf6eca135b7f20cde13vjh",
?   "idx" : 64,?   "name" : "Tuya - Smart Plug 64",?   "nvalue" : 1,?   "stype" : "Switch",?   "switchType" : "On/Off",?   "unit" : 4?}?"

16-7-2020 20:39:42node: 95d6a158.34616msg.payload : boolean
false
//Incomming device row message from domoticz/out, switch was set to off
16-7-2020 20:39:43node: 95d6a158.34616domoticz/out : msg.payload : string[281]
"{?   "Battery" : 255,?   "RSSI" : 12,?   "description" : "",?   "dtype" : "Light/Switch",?   "id" : "bf6eca135b7f20cde13vjh",
?   "idx" : 64,?   "name" : "Tuya - Smart Plug 64",?   "nvalue" : 0,?   "stype" : "Switch",?   "svalue1" : "0",?   "switchType" : "On/Off",
?   "unit" : 4?}?"

16-7-2020 20:39:44node: 95d6a158.34616msg.payload : string[22]
"{"idx":64, "nvalue":0}"

16-7-2020 20:39:45node: 95d6a158.34616msg.payload : boolean
false

16-7-2020 20:39:45node: 95d6a158.34616
domoticz/out : msg.payload : string[261]
"{?   "Battery" : 255,?   "RSSI" : 12,?   "description" : "",?   "dtype" : "Light/Switch",?   "id" : "bf6eca135b7f20cde13vjh",?   "idx" : 64,?   "name" : "Tuya - Smart Plug 64",?   "nvalue" : 0,?   "stype" : "Switch",?   "switchType" : "On/Off",?   "unit" : 4?}?"

From Domoticz Log:
2020-07-16 20:39:32.490 Status: S0 Meter:ID:99001:I:10:M1:0:9847:M2:0:3234:M3:0:980:M4:0:6708:M5:0:0:M6:0:1397:M7:0:1:M8:0:1134:M9:0:0:M10:0:2705:M11:0:3452:M12:0:0
2020-07-16 20:39:33.763 (Tuya) onCommand: On, level (1) Color:
2020-07-16 20:39:33.763 (Tuya - Smart Plug 64) Updating device from 0:'' to have values 1:'1'.
2020-07-16 20:39:33.867 MQTT: Topic: domoticz/in, Message: {"idx":64, "nvalue":1}
2020-07-16 20:39:33.479 Status: User: Admin initiated a switch command (64/Tuya - Smart Plug 64/On)
2020-07-16 20:39:37.776 (Tuya) onCommand: Off, level (1) Color:
2020-07-16 20:39:37.776 (Tuya - Smart Plug 64) Updating device from 1:'' to have values 0:'0'.
2020-07-16 20:39:37.880 MQTT: Topic: domoticz/in, Message: {"idx":64, "nvalue":0}
2020-07-16 20:39:37.483 Status: User: Admin initiated a switch command (64/Tuya - Smart Plug 64/Off) 

If you need more/other debug info, please tell me how to generate this. Thank you for your help

**Comment by tizzen33** [comment]
Hi,
Cool that you're using the plugin. I've used it as well in combination with MQTT and I'm pretty sure where your problem resides :).

Sending this type of message `{"idx":64, "nvalue":0}` to `domoticz/in` will only update the status of the device without sending the onCommand. 
Try sending a different message: `{"command": "switchlight", "idx": 64, "switchcmd": "Off" }`. This will trigger the onCommand which will send the call to the Tuya API.

Let me know if this solves your issue.
Kind regards
tizzen

**Comment by heinohein** [comment]
Thank you for your help. It definitily solved the problem.

**Comment by tizzen33** [comment]
Glad it worked out!
