### ISSUE TITLE
Dim Light Bulbs

### ISSUE THREAD

**Issue by michelscholte** [tizzen33/domoticz-tuyacloud-plugin#8]
Dear developer,

Great work. Plugin works like a charm. I used it with a few Wall Outlets.

Question: Is it possible to dim a light bulb with this Plugin? I want to buy suchs bulbs, but I want to be sure it works? 

Sorry. Just read the description in Domoticz that only power plugs can be discovered and used.
Can you make a change to these plugin so that dimming and on/off bulbs is possible?

Thanks in advantage.

**Comment by tizzen33** [comment]
Hi

At the moment, there is no support for dimming lights but it is possible with the API.

Kind regards
Tizzen

**Comment by tizzen33** [comment]
Hi, I updated the plugin to support dimming of light bulbs. I don't have a light bulb myself, so it would be great if you could test it. Please download the newest version here: [/tizzen33-patch-1/plugin.py](https://github.com/tizzen33/domoticz-tuyacloud-plugin/blob/tizzen33-patch-1/plugin.py)
